services:
  tika:
    build:
      context: .
      dockerfile: Dockerfile.tika
    ports:
      - "9998:9998"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/tika"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  document-processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
    ports:
      - "3000:3000"  
    environment:
      - TIKA_SERVER_URL=http://tika:9998
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./completed:/app/completed 
    depends_on:
      - tika